spring.application.name=Zomato-System
Spring.datasource.url = jdbc:mysql://localhost:3306/zomatodb
Spring.datasource.username=zaid
Spring.datasource.password=password123
Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
